### ISSUE TITLE
Github footer links broken

### ISSUE THREAD

**Issue by WintersMichael** [2factorauth/frontend#23]
The footer simply links to https://github.com/

I believe https://github.com/2factorauth/frontend/blob/master/layouts/partials/base.footer.html needs to reference
```go
{{ .Params.default.github }}
```
 instead of
```go
{{ .Site.Params.General.github }}
```
but I'm unable to test.

**Comment by Carlgo11** [comment]
Thanks for pointing that out @WintersMichael!
