### ISSUE TITLE
Search view shows categories in columns

### ISSUE THREAD

**Issue by hkamran80** [2factorauth/frontend#7]
<img width="1680" alt="2fa-beta-search-broken-1" src="https://user-images.githubusercontent.com/16967687/208271412-b1fc2094-b5e7-450a-8afc-dc3bc87cf676.png">
<img width="1680" alt="2fa-beta-search-broken-2" src="https://user-images.githubusercontent.com/16967687/208271415-ffed4eff-8113-4d09-8a2f-74a97679de6a.png">
<img width="1680" alt="2fa-beta-search-broken-3" src="https://user-images.githubusercontent.com/16967687/208271416-f45a3189-3f28-46b6-9b6c-9395663601b3.png">

I'll try to fix it if I get a chance

**Comment by Carlgo11** [comment]
I know there's a problem when switching viewports between mobile and desktop (and vice versa) that can manifest as this but I'm unable to reproduce this bug without changing viewports during a session.

For me it looks like this (on Firefox 107) :
![screenshot](https://user-images.githubusercontent.com/3535780/208310694-f3ac802c-683b-49ee-b1ea-1072c475320a.png)

**Comment by Carlgo11** [comment]
And on Chromium v108:
![screenshot](https://user-images.githubusercontent.com/3535780/208311273-a7035727-d294-4ccf-8b63-7b5381890950.png)

**Comment by hkamran80** [comment]
Hard refresh fixed it. Weird that it didn't fix it yesterday.
