### ISSUE TITLE
Extra spacing when searching for sites in last category

### ISSUE THREAD

**Issue by ApCoder123** [2factorauth/frontend#8]
Similar issue to https://github.com/2factorauth/twofactorauth/pull/5760

![image](https://user-images.githubusercontent.com/20560218/208298617-6ab0c2e6-95f0-4cac-b39f-42e2130170ee.png)

**Comment by Carlgo11** [comment]
That's really weird. What browser are you on?
I tried on Chrome and Firefox and I don't see any spacing issue :thinking: 
![Chrome](https://user-images.githubusercontent.com/3535780/208311417-86ab4052-4289-4563-943a-5ee0c5b33e2c.png)
![Firefox](https://user-images.githubusercontent.com/3535780/208311453-e0f9d23e-dfba-4e81-b98e-eb502a6b3e0c.png)

**Comment by ApCoder123** [comment]
I was using Chrome, but the issue no longer seems to be occurring?
